### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by SergeyShk** [machine-intelligence-laboratory/OptimalNumberOfTopics#51]
Запускаю питоновский код из примера на своих данных и получаю следующую ошибку:

```
    194         document_words = self._get_words(document)
    195         top_words = self._get_top_words(topic, word_topic_relatednesses)
--> 196         top_words_cooccurrences = self._get_top_words_cooccurrences(top_words, document_words)
    197 
    198         return self._compute_newman_coherence(

~/Data Science/Notebooks/topnum/topnum/scores/sophisticated_toptok_coherence_score.py in _get_top_words_cooccurrences(self, top_words, document_words)
    264         self._update_cooccurrences(cooccurrences, top_words, words_num_appearances_in_window)
    265 
--> 266         last_word_in_window = start_window[0]
    267 
    268         for w in document_words[self._window:]:

IndexError: list index out of range
```

**Comment by Alvant** [comment]
@SergeyShk спасибо за отзыв!

Такое могло произойти в случае, если в коллекции был пустой документ, например `doc_n` в таком `vw.txt` файле
```
...
doc_k |@word sunny afternoon
...
doc_n |@word
...
```

Этот случай в самом деле валидный! и для него код поправил.
Если ошибка сохранится, то будем ещё выяснять.

Также в прилинкованном реквесте поправил ещё заранее пару деталей, чтобы библиотека работала с TopicNet последней версии 0.7.0

**Comment by Alvant** [comment]
(то есть теперь, если у вас был ТопикНет версии ниже 0.7.0, то надо его обновить до последней версии `pip install --upgrade topicnet`)

**Comment by Alvant** [comment]
В общем, раз проблемы вроде как больше нет, то закрываю)

**Comment by SergeyShk** [comment]
Да, вроде как работает теперь. Спасибо.
